### ISSUE TITLE
Permettre l'utilisation du moteur de calculs en NodeJS

### ISSUE THREAD

**Issue by guillett** [mquandalle/mesaidesvelo#81]
cf. https://github.com/betagouv/aides-jeunes/issues/1957

Dans le simulateur d'aides pour les jeunes, le calcul des aides peut être fait dans le front mais aussi dans le back (notamment pour générer les emails récapitulatifs).

En l'état une tentative d'utilisation en NodeJs a généré :

```
internal/modules/cjs/loader.js:438
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/thomas/repos/aides-jeunes/node_modules/aides-velo/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/thomas/repos/aides-jeunes/velo.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by mquandalle** [comment]
Merci pour le retour, c'est corrigé dans `1.0.2`.

**Comment by guillett** [comment]
Tellement efficace, merci beaucoup.
